name: "GAINSWave Columbus"
description: "GAINSWave Columbus"
baseurl: ''
url: "http://gainswavecolumbus.com"


physician_name: "Dr. ELIZABETH TUTTLE"
practice_name: "Columbus Wellness Medicine, LLCs"
logo: "logo.jpg"
doctor_image: "doctor.jpg"
address: "3807 Attucks Drive, Powell, OH, United States  43065"
phone: ""
phone_link: ""
map_location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3049.448428892052!2d-83.09211078496239!3d40.15456847939652!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8838ed901d36a245%3A0xd26e4bb27d8c3d19!2sColumbus+Wellness+Medicine!5e0!3m2!1svi!2s!4v1504933824368"

streetaddress: '3807 Attucks Drive'
city: 'Powell'
state: 'OH'
zipcode: ' 43065'

facebook_url: "https://www.facebook.com/gainswave/"
twitter_url: "https://twitter.com/gainswave"
youtube_url: "https://www.youtube.com/channel/UCWWUCBBqt1nca2TCRIEUNqw"

keyword_location: "Powell, OH,CLEVELAND, OH,CINCINNATI, OH,INDIANAPOLIS, IN"
title: "GAINSWave Columbus - Columbus Wellness Medicine, LLCs"
site_description: "Columbus Wellness Medicine, LLCs is located at 3807 Attucks Drive, Powell, OH. Request your GAINSWaveâ„¢ appointment today."

home_page_banner_tagline: "A Breakthrough Solution for Men Seeking Better Erections & Optimal Sexual Performance"
home_page_video1: "<iframe width='560' height='220' src='https://www.youtube.com/embed/S_iNBM_kqxM' frameborder='0' allowfullscreen></iframe>"
home_page_video2: "<iframe width='560' height='220' src='https://www.youtube.com/embed/clvHBG5co24?list=PLpU9rK7DkkiGPG8MSIxa0JwbkTXO__ZE5' frameborder='0' allowfullscreen></iframe>"
home_page_video3: "<iframe width='560' height='220' src='https://www.youtube.com/embed/v7tILWT-ucU?list=PLpU9rK7DkkiGPG8MSIxa0JwbkTXO__ZE5' frameborder='0' allowfullscreen></iframe>"

paginate: 5
paginate_path: "/blog/page:num"

include: [.htaccess]
permalink: /:title/
